name: specreboot
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.12
  - numpy<2.2
  - matchms==0.31.0
  - ipykernel
  - spec2vec
  - pytest
  - pip

  - pip:
     - ms2deepscore==2.11
