"""
===============================================================================
Behavior Conservation (Golden Master) Test Suite
===============================================================================

OVERVIEW:
    This test suite ensures zero behavior regression during refactoring of
    `networking.py`. It uses a "Golden Master" testing pattern to capture and 
    verify the exact output graph structures, node/edge attributes, and cluster 
    assignments generated by public API methods.

COVERAGE:
    - build_base_graph
    - build_thresh_graph
    - build_core_rescue_graph

HOW IT WORKS:
    1. Generates deterministic synthetic similarity and support matrices (seed: 42).
    2. Runs all public graph-building methods through various parameter setups
       (testing thresholding, max_links degree capping, and component filtering).
    3. Compares generated graph structures against `golden_behavior.json`.

USAGE:
    Run test suite:
        $ pytest test_conservation_of_behavior.py

    Generate or update the golden reference snapshot:
        $ pytest test_conservation_of_behavior.py --update-golden

FILE DEPENDENCIES:
    - networking.py         (Module under test)
    - golden_behavior.json  (Reference output file, created on first run/update)
===============================================================================
"""

import json
import numpy as np
import pandas as pd
import networkx as nx
import pytest

from specreboot.networking.networking import (
    build_base_graph,
    build_thresh_graph,
    build_core_rescue_graph,
)


@pytest.fixture
def synthetic_data() -> tuple[pd.DataFrame, pd.DataFrame]:
    """Generate reproducible symmetric test matrices for similarity and support."""
    np.random.seed(42)
    num_nodes = 100

    # Random symmetric similarity matrix with 1s on diagonal
    sim_data = np.random.uniform(0.1, 0.95, size=(num_nodes, num_nodes))
    sim_data = (sim_data + sim_data.T) / 2.0
    np.fill_diagonal(sim_data, 1.0)

    # Random symmetric support matrix with 1s on diagonal
    sup_data = np.random.uniform(0.0, 1.0, size=(num_nodes, num_nodes))
    sup_data = (sup_data + sup_data.T) / 2.0
    np.fill_diagonal(sup_data, 1.0)

    labels = [f"node_{i}" for i in range(num_nodes)]
    df_mean_sim = pd.DataFrame(sim_data, index=labels, columns=labels)
    df_support = pd.DataFrame(sup_data, index=labels, columns=labels)

    return df_mean_sim, df_support


def _extract_graph_summary(graph: nx.Graph) -> dict:
    """Extract deterministic metrics and metadata from a networkx Graph."""
    nodes_summary = {
        node: graph.nodes[node]
        for node in sorted(graph.nodes())
    }

    edges_summary = [
        {
            "u": str(u),
            "v": str(v),
            "data": dict(data),
        }
        for u, v, data in sorted(graph.edges(data=True), key=lambda x: (str(x[0]), str(x[1])))
    ]

    return {
        "num_nodes": graph.number_of_nodes(),
        "num_edges": graph.number_of_edges(),
        "nodes": nodes_summary,
        "edges": edges_summary,
    }


def compute_behavior_snapshot(df_sim: pd.DataFrame, df_sup: pd.DataFrame, tmp_path) -> dict:
    """Run all public methods across representative configurations."""
    snapshot = {}

    # 1. Test build_base_graph
    g_base = build_base_graph(
        df_sim,
        df_sup,
        sim_threshold=0.6,
        max_links=3,
        link_method="mutual",
        max_component_size=5,
        output_file=str(tmp_path / "tmp_base.graphml"),
    )
    snapshot["build_base_graph"] = _extract_graph_summary(g_base)

    # 2. Test build_thresh_graph
    g_thresh = build_thresh_graph(
        df_sim,
        df_sup,
        sim_threshold=0.5,
        support_threshold=0.4,
        max_links=2,
        link_method="single",
        max_component_size=4,
        output_file=str(tmp_path / "tmp_thresh.graphml"),
    )
    snapshot["build_thresh_graph"] = _extract_graph_summary(g_thresh)

    # 3. Test build_core_rescue_graph
    g_rescue = build_core_rescue_graph(
        df_sim,
        df_sup,
        sim_core=0.7,
        support_core=0.3,
        sim_rescue_min=0.3,
        support_rescue=0.5,
        max_links=4,
        link_method="mutual",
        max_component_size=6,
        output_file=str(tmp_path / "tmp_rescue.graphml"),
    )
    snapshot["build_core_rescue_graph"] = _extract_graph_summary(g_rescue)

    return snapshot


def test_conservation_of_behavior(synthetic_data, tmp_path, request):
    """Verifies that current output strictly matches the golden snapshot."""
    df_sim, df_sup = synthetic_data
    golden_file = request.config.rootpath / "tests" / "data" / "golden_behavior.json"
    update_golden = request.config.getoption("--update-golden", default=False)

    current_snapshot = compute_behavior_snapshot(df_sim, df_sup, tmp_path)

    # Automatically write golden file if missing or if --update-golden flag is passed
    if update_golden or not golden_file.exists():
        with open(golden_file, "w", encoding="utf-8") as f:
            json.dump(current_snapshot, f, indent=2)
        pytest.skip(f"Golden reference saved/updated at {golden_file}.")

    with open(golden_file, "r", encoding="utf-8") as f:
        golden_snapshot = json.load(f)

    assert current_snapshot == golden_snapshot, (
        "Behavior change detected! Graph structures or metadata do not match "
        "the reference file in golden_behavior.json."
    )


def pytest_addoption(parser):
    """Add CLI flag to overwrite/update the golden reference file."""
    parser.addoption(
        "--update-golden",
        action="store_true",
        default=False,
        help="Overwrite the existing golden_behavior.json snapshot with current execution results.",
    )