library: null # should be specified by user
query: null # should be specified by user 

library_cleaned: null  # not required 
query_cleaned: null # not required

outdir: "."

precursor_tolerance: 0.02
analog_search: true
top_n: 100
B: 100
similarity_type: ms2ds
score_threshold: 0.7
flash_tolerance: 0.01

binning_decimals: 2
seed: 42

ms2deepscore_model_path: null # optional
spec2vec_model_path: null # optional